# Generated by Django 4.2.2 on 2023-07-22 08:51

import charityapp.user_profiles.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Volunteer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('DO_NOT_SHOW', 'Do not show')], default=charityapp.user_profiles.models.Gender['DO_NOT_SHOW'], max_length=30)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('phone_number', models.IntegerField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('interests', models.TextField()),
                ('charity_history', models.ManyToManyField(to='work.charitycampaigns')),
                ('donation_history', models.ManyToManyField(to='work.donationcampaigns')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Sponsor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
                ('website', models.URLField()),
                ('career_field', models.CharField(blank=True, max_length=100, null=True)),
                ('donation_history', models.ManyToManyField(to='work.donationcampaigns')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Member', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('DO_NOT_SHOW', 'Do not show')], default=charityapp.user_profiles.models.Gender['DO_NOT_SHOW'], max_length=30)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('phone_number', models.IntegerField()),
                ('strengths', models.TextField(blank=True, null=True)),
                ('interests', models.CharField(choices=[('ENVIRONMENTAL_CAUSES', 'Environmental causes'), ('HUMANITARIAN_CAUSES', 'Humanitarian causes'), ('DISASTERS_AND_ACCIDENTS_CAUSES', 'Causes of disasters and accidents'), ('ANIMAL_CAUSES', 'Animal causes'), ('OTHER', 'Other')], max_length=33)),
                ('role', models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('VICE_CHAIRMAN', 'Vice Chairman'), ('SECRETARY', 'Secretary'), ('ADMINISTRATOR', 'Administrator'), ('MODERATOR', 'Moderator'), ('CASHIER', 'Cashier'), ('PR', 'Public Relations (PR)'), ('OTHER', 'Other')], max_length=21)),
                ('contribution_history', models.ManyToManyField(to='work.charitycampaigns')),
            ],
        ),
    ]
