# Generated by Django 4.2.2 on 2023-07-22 16:01

import charityapp.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('country', models.CharField(choices=[('COUNTRY', 'Bulgaria')])),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit card')])),
                ('holder_name', models.CharField()),
                ('card_verification_value', models.IntegerField(help_text='Enter the three-digit card verification value (CVV/CVC) from the back of your card.', validators=[charityapp.common.validators.validate_card_verification_value])),
                ('card_number', models.IntegerField(help_text='Enter the three-digit card verification value (CVV/CVC) from the back of your card.', validators=[charityapp.common.validators.validate_card_number])),
                ('card_expiration_month', models.CharField(choices=[('JANUARY', '1'), ('FEBRUARY', '2'), ('MARCH', '3'), ('APRIL', '4'), ('MAY', '5'), ('JUNE', '6'), ('JULY', '7'), ('AUGUST', '8'), ('SEPTEMBER', '9'), ('OCTOBER', '10'), ('NOVEMBER', '11'), ('DECEMBER', '12')], max_length=9)),
                ('card_expiration_year', models.CharField(choices=[('YEAR_23', '23'), ('YEAR_24', '24'), ('YEAR_25', '25'), ('YEAR_26', '26'), ('YEAR_27', '27'), ('YEAR_28', '28'), ('YEAR_29', '29'), ('YEAR_30', '30'), ('YEAR_31', '31'), ('YEAR_32', '32')], max_length=7)),
            ],
        ),
    ]
