# Generated by Django 4.2.2 on 2023-07-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donation_amount',
            field=models.CharField(choices=[('D_10', '10 BGN'), ('D_20', '20 BGN'), ('D_50', '50 BGN'), ('D_100', '100 BGN'), ('D_200', '200 BGN'), ('D_OTHER', 'Other')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
