# Generated by Django 4.2.2 on 2023-07-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_donate_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='donation_amount',
            field=models.CharField(choices=[('BGN_10', '10 BGN'), ('BGN_20', '20 BGN'), ('BGN_50', '50 BGN'), ('BGN_100', '100 BGN'), ('BGN_200', '200 BGN'), ('BGN_OTHER', 'Other')], max_length=9),
        ),
    ]
