# Generated by Django 4.2.2 on 2023-07-23 09:49

import charityapp.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_donate_donation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='card_number',
            field=models.CharField(help_text='Enter the three-digit card verification value (CVV/CVC) from the back of your card.', max_length=19, validators=[charityapp.common.validators.validate_card_number]),
        ),
    ]
