# Generated by Django 4.2.2 on 2023-07-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_donate_card_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donate',
            new_name='Donation',
        ),
    ]
