# Generated by Django 4.2.2 on 2023-07-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityCampaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('motivation', models.TextField()),
                ('type', models.CharField(choices=[('1', 'Environmental Charity'), ('2', 'Children’s Charity'), ('3', 'Human Rights Charity'), ('4', 'Disaster Relief Charity'), ('5', 'Scientific Research Charity'), ('6', 'Senior Citizen Charity'), ('7', 'Cultural Charity'), ('8', 'Animal-Based Charity'), ('9', 'Sports-Based Charity'), ('10', 'Education Charity'), ('11', 'Other')], max_length=50)),
                ('website', models.URLField()),
                ('period', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='DonationCampaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('motivation', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
