# Generated by Django 4.2.2 on 2023-07-03 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcampaigns',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='helperprofiles',
            name='interests',
            field=models.CharField(choices=[('1', 'Environmental causes'), ('2', 'Humanitarian causes'), ('3', 'Causes of disasters and accidents'), ('4', 'Animal causes'), ('5', 'Other')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='helperprofiles',
            name='role',
            field=models.CharField(choices=[('1', 'Chairman'), ('1', 'Vice Chairman'), ('1', 'Secretary'), ('1', 'Administrator'), ('1', 'Moderator'), ('1', 'Cashier'), ('1', 'Public Relations (PR)'), ('1', 'Volunteer'), ('1', 'Field volunteer'), ('1', 'Member of the Club')], max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
