# Generated by Django 4.2.2 on 2023-07-10 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitycampaigns',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2023, 7, 10)),
        ),
        migrations.AlterField(
            model_name='charitycampaigns',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2023, 7, 10)),
        ),
    ]
