# Generated by Django 4.2.2 on 2023-07-03 20:55

import charityapp.charity.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_alter_donationcampaigns_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2), charityapp.charity.models.validate_only_alphanumeric]),
        ),
    ]
