# Generated by Django 4.2.2 on 2023-07-11 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_alter_charitycampaigns_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitycampaigns',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 7, 11), null=True),
        ),
        migrations.AlterField(
            model_name='charitycampaigns',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 7, 11), null=True),
        ),
    ]
