# Generated by Django 4.2.2 on 2023-07-11 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_alter_charitycampaigns_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitycampaigns',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='charitycampaigns',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
