# Generated by Django 4.2.2 on 2023-07-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_charitycampaigns_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitycampaigns',
            name='resume',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
