# Generated by Django 4.2.2 on 2023-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_charitycampaigns_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitycampaigns',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
